engines:
    checkstyle:
        enabled: true
        checks:
            com.puppycrawl.tools.checkstyle.checks.sizes.LineLengthCheck:
                enabled: false
    fixme:
        enabled: true
    csslint:
        enabled: true
        checks:
            important:
                enabled: false
            order-alphabetical:
                enabled: false
    scss-lint:
        enabled: true
        checks:
            ColorVariable:
                enabled: false
            LeadingZero:
                enabled: false
            Indentation:
                enabled: false
            ImportantRule:
                enabled: false
            SelectorFormat:
                enabled: false
    markdownlint:
        enabled: true
        checks:
            MD013:
                enabled: false
            MD029:
                enabled: false
            MD030:
                enabled: false
exclude_patterns:
    - ".Rproj.user"
    - ".Rhistory"
    - ".RData"
    - ".Ruserdata"
    - ".htaccess"
    - "cgi-bin/gDriveFast.pm"
    - "cgi-bin/gDriveMountFast.pl"
    - "cgi-bin/core/packages"
    - "**/*.min.js"
    - "**/*.min.css"
