name: R CI

on:
    push:
        branches:
            - main
        paths:
            - "**/*.Rmd"
            - "**/*.R"
            - ".github/workflows/r.yaml"
    pull_request:
        branches:
            - main
        paths:
            - "**/*.Rmd"
            - "**/*.R"
            - ".github/workflows/r.yaml"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up R
              uses: r-lib/actions/setup-r@v2

            - name: Install dependencies
              run: |
                  Rscript -e 'install.packages(c("renv", "rmarkdown", "knitr", "ltm"))'
                  Rscript -e 'renv::restore()'
